#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <header_file> <libpath> [wrapper_name] [--prefix=NAME] [gcc_options...]"
    echo "Example: $0 /usr/include/stdio.h libc.so.6 libc"
    exit 1
fi

HEADER="$1"
LIBNAME="$2"
shift 2

# Handle --prefix argument
ARGS=("$@")
FILTERED_ARGS=()
WRAPPER_NAME_FROM_FLAG=""

for arg in "${ARGS[@]}"; do
    if [[ "$arg" == --prefix=* ]]; then
        WRAPPER_NAME_FROM_FLAG="${arg#*=}"
    else
        FILTERED_ARGS+=("$arg")
    fi
done

set -- "${FILTERED_ARGS[@]}"

WRAPPER_NAME="${1:-libcall}"

# Check if next arg is likely a wrapper name or a gcc option
if [[ "$1" == -* ]]; then
    WRAPPER_NAME="libcall"
else
    if [[ $# -ge 1 ]]; then
        shift
    fi
fi

if [[ -n "$WRAPPER_NAME_FROM_FLAG" ]]; then
    WRAPPER_NAME="$WRAPPER_NAME_FROM_FLAG"
fi

GCC_OPTS=("$@")

# Portable temp dir creation (Linux/macOS)
TEMP_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'h2bash')
TEMP_C="$TEMP_DIR/temp.c"
TEMP_AUX="$TEMP_DIR/temp.aux"

# Cleanup on exit
trap "rm -rf '$TEMP_DIR'" EXIT

# Create temp C file
echo "#include \"$HEADER\"" > "$TEMP_C"

# Find a suitable GCC that supports -aux-info (Clang does not)
GCC_BIN="gcc"
if ! gcc -aux-info /dev/null -x c /dev/null -c -o /dev/null >/dev/null 2>&1; then
    # Try to find real GCC from Homebrew
    for ver in {14..9}; do
        if command -v "gcc-$ver" >/dev/null; then
            GCC_BIN="gcc-$ver"
            break
        fi
    done
fi

# Run gcc -aux-info
"$GCC_BIN" "${GCC_OPTS[@]}" -aux-info "$TEMP_AUX" -c "$TEMP_C" -o /dev/null >/dev/null 2>&1

USE_CLANG_AST=0
if [[ ! -s "$TEMP_AUX" ]]; then
    # Try Clang AST dump fallback
    if command -v clang >/dev/null; then
        # echo "Trying Clang AST dump..." >&2
        clang -Xclang -ast-dump -fsyntax-only "${GCC_OPTS[@]}" "$TEMP_C" > "$TEMP_AUX" 2>/dev/null
        if grep -q "FunctionDecl" "$TEMP_AUX"; then
            USE_CLANG_AST=1
        fi
    fi
fi

if [[ ! -s "$TEMP_AUX" && "$USE_CLANG_AST" -eq 0 ]]; then
    echo "Error: No prototypes generated. Check header path and gcc options." >&2
    if [[ "$GCC_BIN" == "gcc" ]]; then
        echo "Note: If you are on macOS, the default 'gcc' is likely Clang, which does not support -aux-info." >&2
        echo "Please install real GCC: brew install gcc" >&2
    fi
    exit 1
fi

# Portable uppercase (Bash 3.2 compat)
SIG_ARRAY_NAME="$(echo "$WRAPPER_NAME" | tr '[:lower:]' '[:upper:]')_SIGS"

# Generate the bash script that defines the signatures and wrapper function
cat <<BASH_EOF
#!/usr/bin/env bash

# This script defines the signatures for $LIBNAME and a wrapper function.
# Generated by h2bash.sh

# Ensure callso is loaded
if [[ "\$(type -t callso)" != "builtin" ]]; then
    echo "Error: 'callso' builtin not found. Please load it first." >&2
    return 1
fi

# Check for Bash 4.0+ (required for associative arrays)
if [[ "\${BASH_VERSINFO:-0}" -lt 4 ]]; then
    echo "Error: This library requires Bash 4.0+ (you are using \$BASH_VERSION)." >&2
    return 1
fi

LIB_PATH="$LIBNAME"

declare -A $SIG_ARRAY_NAME

BASH_EOF

# Parse the aux file and append to the bash array
map_type() {
    local t="$1"
    t="${t//const/}"
    t="${t//volatile/}"
    t="${t//restrict/}"
    t="${t//struct/}"
    t="${t//enum/}"
    t="${t//unsigned/u}"
    t="${t//signed/}"
    t="$(echo "$t" | xargs)" 

    if [[ "$t" == *"*"* ]]; then
        if [[ "$t" == *"char"* && "$t" != *"**"* ]]; then echo "str"; return; fi
        echo "ptr"
        return
    fi

    if [[ "$t" == *"void"* ]]; then echo "void"; return; fi
    if [[ "$t" == *"float"* ]]; then echo "f32"; return; fi
    if [[ "$t" == *"double"* ]]; then echo "f64"; return; fi
    if [[ "$t" == *"long"* ]]; then echo "i64"; return; fi
    if [[ "$t" == *"int"* ]]; then
        if [[ "$t" == *"u"* ]]; then echo "u32"; return; fi
        echo "i32"
        return
    fi
    if [[ "$t" == *"short"* ]]; then echo "i32"; return; fi
    if [[ "$t" == *"char"* ]]; then echo "i32"; return; fi
    if [[ "$t" == *"size_t"* ]]; then echo "u64"; return; fi
    if [[ "$t" == *"ssize_t"* ]]; then echo "i64"; return; fi
    if [[ "$t" == *"bool"* ]]; then echo "i32"; return; fi
    
    echo "i32"
}

if [[ "$USE_CLANG_AST" -eq 1 ]]; then
    # Parse Clang AST
    # Format: ... Name 'Signature'
    # We use perl for better regex compatibility on macOS
    # Regex: Look for FunctionDecl, then capture the identifier before the single-quoted signature
    grep "FunctionDecl" "$TEMP_AUX" | perl -ne "print \"\$1|\$2\n\" if / ([a-zA-Z0-9_]+) '([^']+)'/" | while IFS='|' read -r name sig_str; do
        # sig_str is like "void (int, int)"
        ret_type_str="${sig_str%%(*}"
        args_str="${sig_str#*(}"
        args_str="${args_str%)}"
        
        ret_type=$(map_type "$ret_type_str")
        sig="$ret_type"
        
        if [[ -n "$args_str" && "$args_str" != "void" ]]; then
            IFS=',' read -ra ADDR <<< "$args_str"
            for arg in "${ADDR[@]}"; do
                arg_type=$(map_type "$arg")
                sig="$sig $arg_type"
            done
        fi
        
        echo "${SIG_ARRAY_NAME}[\"$name\"]=\"$sig\""
    done
else
    # Parse GCC aux-info
    while read -r line; do
        [[ -z "$line" ]] && continue
        line="${line#*\*/}"
        line="${line#*extern }"
        if [[ "$line" != *"("* ]]; then continue; fi
        
        left="${line%%(*}"
        right="${line#*(}"
        right="${right%);*}"
        left="$(echo "$left" | xargs)"
        name="${left##* }"
        ret_str="${left% $name}"
        
        ret_type=$(map_type "$ret_str")
        
        sig="$ret_type"
        if [[ "$right" != "void" && -n "$right" ]]; then
            IFS=',' read -ra ADDR <<< "$right"
            for arg in "${ADDR[@]}"; do
                arg_type=$(map_type "$arg")
                sig="$sig $arg_type"
            done
        fi
        
        echo "${SIG_ARRAY_NAME}[\"$name\"]=\"$sig\""
    done < "$TEMP_AUX"
fi

cat <<BASH_EOF

# Wrapper function
$WRAPPER_NAME() {
    local func="\$1"
    shift
    local sig="\${${SIG_ARRAY_NAME}[\$func]}"
    
    if [[ -z "\$sig" ]]; then
        echo "Error: Unknown function '\$func'" >&2
        return 1
    fi
    
    callso "\$LIB_PATH" "\$sig" "\$func" "\$@"
}

echo "Loaded signatures for $LIBNAME. Use '$WRAPPER_NAME <Function> [Args...]' to call."

BASH_EOF
